### ISSUE TITLE
man pages from github.io are 404 Not Found

### ISSUE THREAD

**Issue by RalphCorderoy** [9fans/9fans.github.io#2]
Viewing https://9fans.github.io/plan9port/unix/, the links for the man pages, like isalpharune(3) are 404 Not Found: https://9fans.github.io/plan9port/unix/man/isalpharune3.html

**Comment by RalphCorderoy** [comment]
Please indicate here when I should expect to see the fix on the Internet. At the moment, the trail still leads to a 404 despite the URL changing.

```
$ curl -sSg https://9fans.github.io/plan9port/unix/ | grep isalpharune
          <a href="man/man3/isalpharune.html"><i>isalpharune</i>(3)</a>,
$ curl -sSg https://9fans.github.io/plan9port/unix/man/man3/isalpharune.html | grep '<title>'
    <title>Page not found &middot; GitHub Pages</title>
$
```

**Comment by 0intro** [comment]
It should be fixed now.

**Comment by RalphCorderoy** [comment]
Thanks, agreed. Having just run through all the other man-page links on https://9fans.github.io/plan9port/unix/, I'm getting 404s for three:

- fmtstrtod(3)
- regexp9(3) 
- regexp9(7)

Perhaps @bhuntsman can spot an accompany fix to his earlier one?

**Comment by 0intro** [comment]
We don't have HTML versions of the `unix/man` manuals yet. These should be added.
